name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_ARCHS: x86_64 i686 aarch64 armv7l
          CIBW_BUILD: cp37 cp38 cp39 cp310 cp311
          CIBW_ENVIRONMENT_MACOS: SYSTEM_VERSION_COMPAT=0
